### ISSUE TITLE
Editor iframe shows blank when “editor.bombhopper.io” is blocked by a firewall.

### ISSUE THREAD

**Issue by nobody5050** [getkey/ble#3]
Suggest adding some sort of formatted error message.

**Comment by getkey** [comment]
We are talking of the situation where bombhopper.io is not blocked but editor.bombhopper.io is blocked.

- On the editor side, there is nothing I can do since it is blocked.
- On the game side, I could wait for the editor to send a signal, at which point I know it has loaded. If it's not loaded after a certain timeout, I could consider that it failed to load.

This is not a great solution because what's an appropriate timeout is very dependent on one's network speed. In most cases, loading the editor takes no more than a couple seconds, but in some areas it might take 30 or more. Also this is IMO a rare case, I'm not sure why a firewall would block editor.bombhopper.io but not the naked domain.

I don't want to add complexity for an imperfect fix of an uncommon problem, so I'm closing this issue. But if you have another better solution that the one I proposed with the timeout, please reopen. :slightly_smiling_face:

**Comment by nobody5050** [comment]
possible to embed the editor into the game without an iframe by default?

**Comment by getkey** [comment]
In theory yes. In practice, the integration would be pretty complicated.

At the beginning of this project, I made the decision to use an iframe to simplify its development. Putting the editor in the game without an iframe now would need a lot of refactor in both the game and the editor, which is unrealistic.

**Comment by nobody5050** [comment]
ah. Would it be possible to put an error message behind the iframe so if it fails to load it shows?

**Comment by getkey** [comment]
Yes but it would also be visible while the iframe is loading. So that would be confusing 😅

**Comment by nobody5050** [comment]
Ah nuts that’s bad 😅
